name: CI

on:
  pull_request_target:
    types: [opened, reopened, edited, closed, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run xo
        run: npm run lint

      - name: Build
        run: npm run build
